### ISSUE TITLE
Changing resolution 

### ISSUE THREAD

**Issue by omert08** [charlesveasey/ofxMultiGLFWWindow#7]
How can i change single window resolution higher ? 

Thanks

**Comment by charlesveasey** [comment]
Hi,

The example shows how this is done. 

```glfw->setWindow(windows->at(1));
  glfw->initializeWindow();
  ofSetWindowPosition(500, 100);
  ofSetWindowShape(500, 800);
```
However, you should note this addon is no longer supported since these feature are now integrated into the openFrameworks core starting in oF 0.9.0

Charles
